use std::sync::OnceLock;

use crate::deck::Deck;
use crate::games::CardDealer;
use crate::ranking::hand_rank::StandardHandRanker;

use super::HandClass;

const N: usize = HandClass::COUNT;

static BUNDLED: &[u8] = include_bytes!("equity169.bin");

/// All-in preflop equity of every starting-hand class against every other,
/// averaged over the combos that don't share a card. Ties count as half.
pub struct PreflopEquityTable {
    // eq[a * N + b] = equity of a vs b, scaled to 0..=u16::MAX.
    eq: Vec<u16>,
}

impl PreflopEquityTable {
    /// The table shipped with the crate, generated by
    /// `cargo run --release --example gen_preflop_equity` (about ±0.1%).
    pub fn bundled() -> &'static PreflopEquityTable {
        static TABLE: OnceLock<PreflopEquityTable> = OnceLock::new();
        TABLE.get_or_init(|| {
            Self::from_bytes(BUNDLED).expect("bundled preflop equity table is malformed")
        })
    }

    /// Equity of `a` against `b`, from 0.0 to 1.0.
    pub fn equity(&self, a: HandClass, b: HandClass) -> f64 {
        self.eq[a.index() * N + b.index()] as f64 / u16::MAX as f64
    }

    /// Estimates the table by sampling `samples_per_matchup` deals for every
    /// pair of classes. This is slow: use the bundled table unless you need
    /// a different precision.
    pub fn compute(samples_per_matchup: u32) -> Self {
        let row = |a: usize| -> Vec<(usize, f64)> {
            let ca = HandClass::from_index(a).unwrap().combos();
            let mut dealer = CardDealer::new(Deck::all_cards());
            (a + 1..N)
                .map(|b| {
                    let cb = HandClass::from_index(b).unwrap().combos();
                    (
                        b,
                        sample_matchup(&ca, &cb, samples_per_matchup, &mut dealer),
                    )
                })
                .collect()
        };

        #[cfg(feature = "parallel")]
        let rows: Vec<Vec<(usize, f64)>> = {
            use rayon::prelude::*;
            (0..N).into_par_iter().map(row).collect()
        };
        #[cfg(not(feature = "parallel"))]
        let rows: Vec<Vec<(usize, f64)>> = (0..N).map(row).collect();

        let mut eq = vec![u16::MAX / 2 + 1; N * N];
        for (a, cells) in rows.into_iter().enumerate() {
            for (b, e) in cells {
                let v = (e * u16::MAX as f64).round() as u16;
                eq[a * N + b] = v;
                eq[b * N + a] = u16::MAX - v;
            }
        }
        Self { eq }
    }

    /// Serializes as 169 * 169 little-endian u16 values.
    pub fn to_bytes(&self) -> Vec<u8> {
        self.eq.iter().flat_map(|v| v.to_le_bytes()).collect()
    }

    /// Reads the format written by [`Self::to_bytes`].
    pub fn from_bytes(bytes: &[u8]) -> Option<Self> {
        (bytes.len() == N * N * 2).then(|| Self {
            eq: bytes
                .chunks_exact(2)
                .map(|b| u16::from_le_bytes([b[0], b[1]]))
                .collect(),
        })
    }
}

fn sample_matchup(ca: &[Deck], cb: &[Deck], samples: u32, dealer: &mut CardDealer) -> f64 {
    let mut won = 0.0;
    let mut done = 0;
    while done < samples {
        let a = ca[rand::random_range(0..ca.len())];
        let b = cb[rand::random_range(0..cb.len())];
        if u64::from(a) & u64::from(b) != 0 {
            continue;
        }
        let mut used = a;
        used |= b;
        dealer.reset();
        let board = dealer.deal_excluding(5, used);
        let (sa, sb) = (
            StandardHandRanker::score(&(a | board)),
            StandardHandRanker::score(&(b | board)),
        );
        won += match sa.cmp(&sb) {
            std::cmp::Ordering::Greater => 1.0,
            std::cmp::Ordering::Equal => 0.5,
            std::cmp::Ordering::Less => 0.0,
        };
        done += 1;
    }
    won / samples as f64
}

#[cfg(test)]
mod test {
    use super::*;

    fn eq(a: &str, b: &str) -> f64 {
        PreflopEquityTable::bundled().equity(a.parse().unwrap(), b.parse().unwrap())
    }

    #[test]
    fn test_bundled_table_known_matchups() {
        // Published all-in equities for these class matchups.
        for (a, b, expected) in [
            ("AA", "KK", 0.820),
            ("AKs", "QQ", 0.460),
            ("AKo", "22", 0.473),
            ("72o", "AA", 0.120),
        ] {
            let e = eq(a, b);
            assert!(
                (e - expected).abs() < 0.012,
                "{a} vs {b}: {e} (expected about {expected})"
            );
        }
    }

    #[test]
    fn test_bundled_table_is_symmetric() {
        let t = PreflopEquityTable::bundled();
        for a in HandClass::all() {
            assert!((t.equity(a, a) - 0.5).abs() < 1e-4);
            for b in HandClass::all() {
                assert!((t.equity(a, b) + t.equity(b, a) - 1.0).abs() < 1e-4);
            }
        }
    }

    #[test]
    fn test_compute_round_trips() {
        let t = PreflopEquityTable::compute(1);
        let back = PreflopEquityTable::from_bytes(&t.to_bytes()).unwrap();
        assert_eq!(t.eq, back.eq);
        assert!(PreflopEquityTable::from_bytes(&[0; 10]).is_none());
    }
}
